In [ ]:
#a.Импортируйте библиотеку NumPy
import numpy as np


In [ ]:
#b.Создайте массив из 10 нулей
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#c.Создать массив из 10 единиц
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#d.Создать массив из 10 пятерок
a=np.ones(10)*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [20]:
#e.Создать массив из целых чисел от 10 до 50
a=np.arange(10,51,1)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#f.Создать массив из четных чисел от 10 до 50
a=np.arange(10,50,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
#g.Создать матрицу 3х3 с числами от 0 до 8
arr=np.arange(0,9)
arr=arr.reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#h.Создать единичную матрицу 3x3
arr=np.ones(9)
arr=arr.reshape(3,3)
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#i.Используйте NumPy для генерации случайного числа от 0 до 1
a=np.random.rand()
print(a)

0.6485599918587697


In [ ]:
#j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
a=np.random.randn(25)
print(a)

[ 0.01176348  0.54215283  0.12669893  1.29427959 -0.87517702  2.47566631
  0.61533691  1.38377309  0.47950082 -0.08023662  0.29973277  0.58960131
  0.30475867  0.19944782 -1.25140737  1.17329802 -2.17856389 -0.99237087
  0.87953338  0.90771769  0.87602031  0.61869729 -0.5849848   1.08234505
  0.44092597]


In [ ]:
#k.Создайте следующую матрицу, используя функции библиотеки NumPy
arr=np.arange(0.01,1.01,0.01)
arr=arr.reshape(10,10)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [4]:
#l.Дана стартовая матрица. Необходимо написать код, который вернет следующую матрицу (12 - 25) из стартовой
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print (mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
#m.Написать код обращения к элементу, который вернет значение 20 из стартовой матрицы задачи l
mat = np.arange(1,26).reshape(5,5)
print (mat[3][4])

20


In [ ]:
#n.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже (2 7 12)
mat = np.arange(1,26).reshape(5,5)
print ("array =", mat[:3][:,1])

array = [ 2  7 12]


In [ ]:
#o.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже (21,22,23,24,25)
mat = np.arange(1,26).reshape(5,5)
print("array =", mat[4, :])


array = [21 22 23 24 25]


In [ ]:
#p.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже (16 - 25)
mat = np.arange(1,26).reshape(5,5)
print("array =", mat[3:, 0:5])

array = [[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#q.Получить сумму всех значений в стартовой матрице mat
mat = np.arange(1,26).reshape(5,5)
print("Сумма значений =", mat.sum())

Сумма значений = 325


In [ ]:
#r.Получить стандартное отклонение в стартовой матрице mat
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print("Стандартное отклонение =", np.std(mat))

Стандартное отклонение = 7.211102550927978


In [19]:
#s.Получить сумму значений в колонках в стартовой матрице mat
import numpy as np
mat = np.arange(1,26).reshape(5,5)
a = mat[:,0]
print ("Колонка 1", a)
print ("Сумма значений в 1 колонке =", a.sum())
print ("____________________________")

b = mat[:,1]
print ("Колонка 2", b)
print ("Сумма значений в 2 колонке =", b.sum())
print ("____________________________")

c = mat[:,2]
print ("Колонка 3", c)
print ("Сумма значений в 3 колонке =", c.sum())
print ("____________________________")

d = mat[:,3]
print ("Колонка 4", d)
print ("Сумма значений в 4 колонке =", d.sum())
print ("____________________________")

e = mat[:,4]
print ("Колонка 5", e)
print ("Сумма значений в 5 колонке =", e.sum())
print ("____________________________")

Колонка 1 [ 1  6 11 16 21]
Сумма значений в 1 колонке = 55
____________________________
Колонка 2 [ 2  7 12 17 22]
Сумма значений в 2 колонке = 60
____________________________
Колонка 3 [ 3  8 13 18 23]
Сумма значений в 3 колонке = 65
____________________________
Колонка 4 [ 4  9 14 19 24]
Сумма значений в 4 колонке = 70
____________________________
Колонка 5 [ 5 10 15 20 25]
Сумма значений в 5 колонке = 75
____________________________
